server:
  port: 8080

spring:
  application:
    name: "@project.name@"
    version: "@project.version@"

springdoc:
 swagger-ui:
   path: "/swagger-ui.html"

logging:
  file:
    name: logs/app.log
    path: logs
  level:
    root: "DEBUG"
    org:
      springframework:
        web: "DEBUG"
